name: Daily Run of main.py

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Update if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
